modLoader="javafml"
loaderVersion="[47,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="spacevs"
version="1.0.0"
displayName="SpaceVS2"
displayURL="https://mcreator.net"
credits="AAAAA"
authors="Jack_Thee"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.spacevs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.spacevs]]
    modId="valkyrienskies"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.spacevs]]
    modId="valkyrienskies"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

